services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: admin-backend
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-default-key
      - ALLOWED_HOSTS=localhost,127.0.0.1

  frontend:
    build:
      context: ./login-app
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    container_name: admin-frontend
    depends_on:
      - backend
